SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[Cab](
	[CabId] [int] IDENTITY(1,1) NOT NULL,
	[BookId] [bigint] NOT NULL,
	[BookTime] [time](7) NOT NULL,
	[JourneyTime] [bigint] NOT NULL,
	[JourneyPlace] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_Cab] PRIMARY KEY CLUSTERED 
(
	[CabId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO

